Made some changes to make configuring openvswitch easier.

diff --git a/INSTALL/smallDesktopCloud/util/network-fns b/INSTALL/smallDesktopCloud/util/network-fns
--- a/INSTALL/smallDesktopCloud/util/network-fns
+++ b/INSTALL/smallDesktopCloud/util/network-fns
@@ -173,3 +173,69 @@ get_device_ipaddr () {
 
   ip -f inet address show dev ${CLOUD_DATA_COMPUTE_DEVICE} | grep -e "inet" | sed -e "s/^.*inet //" -e "s/brd.*$//" -e "s/\/[0-9]*//"
 }
+
+
+# For neutron/openvswitch networking we want to move the static address of a physical
+# device to a bridge.
+# Usage: move_ip_from_phy_to_bridge <phyDeivceName> <promisc> <bridgeName>
+# <phyDeviceName> - like 'em1'.
+# <promisc>       - promiscuous mode 'yes' or 'no'.
+# <bridgeName>    - name of the bridge device like 'br-ex'
+move_ip_from_phy_to_bridge () {
+
+  if [ $# -ne 3 ] ; then
+    echo "Need 3 arguments to function ${FUNCNAME[0]}."
+    exit 1
+  fi
+
+  # Config files for the network devices.
+  IFCFG_DEVICE=/etc/sysconfig/network-scripts/ifcfg-$1
+  IFCFG_BRIDGE=/etc/sysconfig/network-scripts/ifcfg-$3
+
+  # Make sure we have not already done the work.
+  if [ -f ${IFCFG_BRIDGE} ] ; then
+    echo "# Bridge file '${IFCFG_BRIDGE}' already exists. Assuming that we don't have to modify it."
+    return
+  fi
+
+  # Make sure that the physical device has a static address.
+  grep -e "^IPADDR" ${IFCFG_DEVICE} > /dev/null
+  if [ $? -ne 0 ] ; then
+    echo "# The config file for device $1 has not been setup to be static."
+    echo "!!!!! Unable to continue with bridge setup."
+    exit 1
+  fi
+
+  touch ${IFCFG_BRIDGE}
+  echo "DEVICE=${3}" >> ${IFCFG_BRIDGE}
+  echo "TYPE=Bridge" >> ${IFCFG_BRIDGE}
+  echo "ONBOOT=no" >> ${IFCFG_BRIDGE}
+  echo "BOOTPROTO=none" >> ${IFCFG_BRIDGE}
+  # get IPADDR, NETMASK and GATEWAY from the physical device config file.
+  EXT_IPADDR=$(grep -e "IPADDR[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//")
+  echo "IPADDR=${EXT_IPADDR}" >> ${IFCFG_BRIDGE}
+  EXT_NETMASK=$(grep -e "NETMASK[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//")
+  echo "NETMASK=${EXT_NETMASK}" >> ${IFCFG_BRIDGE}
+  EXT_GATEWAY=$(grep -e "^[ ]*GATEWAY[ ]*=" ${IFCFG_DEVICE} | sed -e "s/^.*=[ ]*//" )
+  if [ "${EXT_GATEWAY}" != "" ] ; then
+    echo "GATEWAY=${EXT_GATEWAY}" >> ${IFCFG_BRIDGE}
+  fi
+
+  echo "# Modifying file '$1'."
+  # comment out the static IP parameters
+  sed -i -e "/^[ ]*IPADDR[ ]*=/s/^/#/" ${IFCFG_DEVICE}
+  sed -i -e "/^[ ]*NETMASK[ ]*=/s/^/#/" ${IFCFG_DEVICE}
+  sed -i -e "/^[ ]*GATEWAY[ ]*=/s/^/#/" ${IFCFG_DEVICE}
+  sed -i -e "/^[ ]*BOOTPROTO[ ]*=/s/=.*/=none/" ${IFCFG_DEVICE}
+  grep -e "PROMISC[ ]*=" ${IFCFG_DEVICE} > /dev/null
+  if [ "$?" == "0" ] ; then
+    # just change the value and uncomment.
+    sed -i -e "/PROMISC/s/^.*\$/PROMISC=$2/" ${IFCFG_DEVICE}
+  else
+    # add the value
+    sed -i -e "\$ a\
+PROMISC=$2" ${IFCFG_DEVICE}
+  fi
+
+}
+
diff --git a/INSTALL/smallDesktopCloud/util/params-network b/INSTALL/smallDesktopCloud/util/params-network
--- a/INSTALL/smallDesktopCloud/util/params-network
+++ b/INSTALL/smallDesktopCloud/util/params-network
@@ -4,6 +4,12 @@
 # - The control and networking functions must NOT be on 
 #   the same host.
 ############################################################
+
+# What distribution are we on
+OS_DIST=$(lsb_release -i | cut -f2)
+OS_VERSION=$(lsb_release -r | cut -f2)
+
+
 # Used by router and networking nodes.
 CLOUD_EXT_NETMASK=255.255.255.0
 CLOUD_EXT_DOMAIN=ext.armored
@@ -72,8 +78,19 @@ CLOUD_DATA_NETWORKING_IPADDR=10.0.0.253
 
 # For RHEL we use the ethX devices. For Feorda 19+ we use the
 # pXpY devices.
-#CLOUD_EXT_COMPUTE_DEVICE=em1
-CLOUD_EXT_COMPUTE_DEVICE=eth0
+if [ "x${OS_DIST}" == "xFedora" ] ; then
+  CLOUD_EXT_COMPUTE_DEVICE=em1
+  CLOUD_DATA_COMPUTE_DEVICE=p5p1
+elif [ "x${OS_DIST}" == "xCentOS" ] ; then
+  CLOUD_EXT_COMPUTE_DEVICE=eth0
+  CLOUD_DATA_COMPUTE_DEVICE=eth1
+else
+  echo "#########################"
+  echo "ERROR: Dont know what to do with distribution =${OS_DIST} in script 'params-network'."
+  echo "#########################"
+  exit 1
+fi
+
 CLOUD_EXT_COMPUTE_IPADDR_PREFIX=10.100.0
 # A number will be added to the CLOUD_EXT_COMPUTE_HOSTNAME_PREFIX to
 # get the compute hostname.
@@ -81,6 +98,7 @@ CLOUD_EXT_COMPUTE_HOSTNAME_PREFIX=compute
 
 # For RHEL we use the ethX devices. For Feorda 19+ we use the
 # pXpY devices.
-#CLOUD_DATA_COMPUTE_DEVICE=p5p1
-CLOUD_DATA_COMPUTE_DEVICE=eth1
 CLOUD_DATA_COMPUTE_IPADDR_PREFIX=10.0.0
+
+CLOUD_EXT_COMPUTE_BRIDGE=xenbr0
+CLOUD_DATA_COMPUTE_BRIDGE=xenbr1
